// <auto-generated />
using System;
using AgrotutorAPI.Data.Postgresql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AgrotutorAPI.Data.Postgresql.Migrations
{
    [DbContext(typeof(AgrotutorContext))]
    [Migration("20190329145649_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AgrotutorAPI.Domain.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivityType");

                    b.Property<string>("AmountApplied");

                    b.Property<string>("AmountSold");

                    b.Property<string>("AppliedProduct");

                    b.Property<string>("Comment");

                    b.Property<double>("Cost");

                    b.Property<DateTime>("Date");

                    b.Property<double>("Dose");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("NumberOfSeeds");

                    b.Property<string>("ParcelId");

                    b.Property<int?>("PlotArea");

                    b.Property<int>("PlotId");

                    b.Property<double>("Price");

                    b.Property<string>("ProductObtained");

                    b.Property<int?>("SellingPrice");

                    b.Property<string>("Sown");

                    b.Property<double>("WeightOfSeeds");

                    b.Property<string>("Yield");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("AgrotutorAPI.Domain.Delineation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PlotId");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.ToTable("Delineations");
                });

            modelBuilder.Entity("AgrotutorAPI.Domain.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Path");

                    b.Property<int?>("PlotId");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.ToTable("MediaItem");
                });

            modelBuilder.Entity("AgrotutorAPI.Domain.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClimateType");

                    b.Property<int>("CropType");

                    b.Property<string>("DeviceID");

                    b.Property<bool>("Irrigated");

                    b.Property<int>("MaturityType");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("AgrotutorAPI.Domain.Activity", b =>
                {
                    b.HasOne("AgrotutorAPI.Domain.Plot", "Plot")
                        .WithMany("Activities")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgrotutorAPI.Domain.Delineation", b =>
                {
                    b.HasOne("AgrotutorAPI.Domain.Plot")
                        .WithMany("Delineation")
                        .HasForeignKey("PlotId");

                    b.OwnsOne("AgrotutorAPI.Domain.Position", "Position", b1 =>
                        {
                            b1.Property<int>("DelineationId");

                            b1.Property<double?>("Accuracy");

                            b1.Property<double?>("Altitude");

                            b1.Property<double?>("Course");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.Property<double?>("Speed");

                            b1.Property<DateTimeOffset>("Timestamp");

                            b1.HasKey("DelineationId");

                            b1.ToTable("Delineations");

                            b1.HasOne("AgrotutorAPI.Domain.Delineation")
                                .WithOne("Position")
                                .HasForeignKey("AgrotutorAPI.Domain.Position", "DelineationId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("AgrotutorAPI.Domain.MediaItem", b =>
                {
                    b.HasOne("AgrotutorAPI.Domain.Plot")
                        .WithMany("MediaItems")
                        .HasForeignKey("PlotId");
                });

            modelBuilder.Entity("AgrotutorAPI.Domain.Plot", b =>
                {
                    b.OwnsOne("AgrotutorAPI.Domain.Position", "Position", b1 =>
                        {
                            b1.Property<int>("PlotId");

                            b1.Property<double?>("Accuracy");

                            b1.Property<double?>("Altitude");

                            b1.Property<double?>("Course");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.Property<double?>("Speed");

                            b1.Property<DateTimeOffset>("Timestamp");

                            b1.HasKey("PlotId");

                            b1.ToTable("Plots");

                            b1.HasOne("AgrotutorAPI.Domain.Plot")
                                .WithOne("Position")
                                .HasForeignKey("AgrotutorAPI.Domain.Position", "PlotId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
